Updated

diff --git a/config/pre-commit b/config/pre-commit
--- a/config/pre-commit
+++ b/config/pre-commit
@@ -17,16 +17,24 @@ export gErr=0
 export gSrc=${BASH_SOURCE##*/}
 
 # --------------------
-fIsBinary()
-{
+fIsBinary() {
     local pFile="$1"
-    grep -Hm1 '^' <"$pFile" 2>&1 | grep -qi 'binary'
+
+    grep -Hm1 '^' <"$pFile" 2>&1 | grep -qi 'binary' >/dev/null 2>&1
     # Copied from: https://unix.stackexchange.com/questions/275516/is-there-a-convenient-way-to-classify-files-as-binary-or-text
+    return $?
 } # fIsBinary
 
 # --------------------
-fReport()
-{
+fIsBash() {
+    local pFile="$1"
+
+    head -n 2 <$pFile | grep -Eq '#!/bin/bash|#!/usr/bin/env bash' >/dev/null 2>&1
+    return $?
+} # fIsBash
+
+# --------------------
+fReport() {
     local pExpect=$1
     local pResult=$2
     local pFile=$3
@@ -34,23 +42,23 @@ fReport()
     local pLine=$5
     local tErr=0
 
-    if [ $pExpect -eq 0 ] && [ $pResult -ne 0 ]; then
+    if [[ $pExpect -eq 0 && $pResult -ne 0 ]]; then
         tErr=1
     fi
-    if [ $pExpect -eq 1 ] && [ $pResult -eq 0 ]; then
+    if [[ $pExpect -eq 1 && $pResult -eq 0 ]]; then
         tErr=1
     fi
-    if [ $tErr -eq 0 ]; then
+    if [[ $tErr -eq 0 ]]; then
         return 0
     fi
 
     let ++gErr
-    if [ "$gVerbose" = "true" ]; then
+    if [[ "$gVerbose" = "true" ]]; then
         echo "$pFile $pMsg [$gSrc:$pLine]"
     fi
     gFileList="$gFileList $pFile"
     git reset HEAD $pFile >/dev/null 2>&1
-    if [ "${pFile%!*}" != "$pFile" ]; then
+    if [[ "${pFile%!*}" != "$pFile" ]]; then
         pFile=$(echo $pFile | tr '!' ' ')
         git reset HEAD "$pFile" >/dev/null 2>&1
     fi
@@ -58,10 +66,9 @@ fReport()
 } # fReport
 
 # --------------------
-fEnabled()
-{
+fEnabled() {
     tEnabled=$(git config --get --bool gitproj.hook.pre-commit-enabled)
-    if [ "$tEnabled" != "true" ]; then
+    if [[ "$tEnabled" != "true" ]]; then
         echo "Skipping pre-commit"
         exit 0
     fi
@@ -70,13 +77,12 @@ fEnabled()
 } # fEnabled
 
 # --------------------
-fCheckFileNames()
-{
+fCheckFileNames() {
     local tFile
     local tResult
 
     tResult=$(git config --get --bool gitproj.hook.check-file-names)
-    if [ "$tResult" != "true" ]; then
+    if [[ "$tResult" != "true" ]]; then
         return 0
     fi
 
@@ -100,7 +106,7 @@ fCheckFileNames()
         fReport 1 $? $tFile "has trailing period" $LINENO || continue
     done
 
-    if [ -n "$gFileList" ]; then
+    if [[ -n "$gFileList" ]]; then
         let ++gErr
         echo
         echo "These files are not valid:"
@@ -119,14 +125,13 @@ EOF
 } # fCheckFileNames
 
 # --------------------
-fCheckWhiteSpace()
-{
+fCheckWhiteSpace() {
     local tFile
     local tResult
     # Note: DOS EOL files will give a false report.
 
     tResult=$(git config --get --bool gitproj.hook.check-whitespace)
-    if [ "$tResult" != "true" ]; then
+    if [[ "$tResult" != "true" ]]; then
         return 0
     fi
 
@@ -135,10 +140,10 @@ fCheckWhiteSpace()
         tFile=${tFile%%:*}
         fReport 0 1 $tFile "trailing whitespace" $LINENO
     done
-    if [ -n "$gFileList" ]; then
+    if [[ -n "$gFileList" ]]; then
         let ++gErr
         echo
-        echo "These files had trailing whitespaces:"
+        echo "These files had trailing whitespaces (fix with: rm-trailing-sp):"
         echo "$gFileList" | fmt -w 10
         echo
     fi
@@ -146,28 +151,27 @@ fCheckWhiteSpace()
 } # fCheckWhiteSpace
 
 # --------------------
-fCheckForTabs()
-{
+fCheckForTabs() {
     local tFile
     local tResult
     local tIncList
     local tExcList
 
     tResult=$(git config --get --bool gitproj.hook.check-for-tabs)
-    if [ "$tResult" != "true" ]; then
+    if [[ "$tResult" != "true" ]]; then
         return 0
     fi
 
     tIncList=$(git config --get gitproj.hook.tab-include-list)
     tExcList=$(git config --get gitproj.hook.tab-exclude-list)
-    if [ -z "$tIncList" ]; then
+    if [[ -z "$tIncList" ]]; then
         tIncList='*'
     fi
 
     # If there are tab, in tIncList, but not tExcList, print file
     # Also skip binary files
     for tFile in $(git diff --cached --name-only --diff-filter=ACR $gAgainst | tr ' ' '!'); do
-        if [ ! -f "$tFile" ]; then
+        if [[ ! -f "$tFile" ]]; then
             continue
         fi
         if fIsBinary $tFile; then
@@ -176,7 +180,7 @@ fCheckForTabs()
         if $(echo $tFile | grep -qvE "$tIncList"); then
             continue
         fi
-        if [ -n "$tExcList" ]; then
+        if [[ -n "$tExcList" ]]; then
             if $(echo $tFile | grep -qE "$tExcList"); then
                 continue
             fi
@@ -188,10 +192,10 @@ fCheckForTabs()
         fi
     done
 
-    if [ -n "$gFileList" ]; then
+    if [[ -n "$gFileList" ]]; then
         let ++gErr
         echo
-        echo "These files had tabs in them:"
+        echo "These files had tabs in them (fix with: expand or bash-fmt):"
         echo "$gFileList" | fmt -w 10
         echo
     fi
@@ -199,22 +203,132 @@ fCheckForTabs()
 } # fCheckForTabs
 
 # --------------------
-# See: check-shfmt.sh
-#fCheckSyntax
-    # bash -n
-#fCheckShell
-    # shellcheck
-# fCheckFmt
-    # shfmt
+fCheckSyntax() {
+    local tFile
+    local tResult
+
+    tResult=$(git config --get --bool gitproj.hook.check-bash-syntax)
+    if [[ "$tResult" != "true" ]]; then
+        return 0
+    fi
+
+    gFileList=""
+    for tFile in $(git diff --cached --name-only --diff-filter=ACR $gAgainst | tr ' ' '!'); do
+        if [[ ! -f "$tFile" ]]; then
+            continue
+        fi
+        if fIsBinary $tFile; then
+            continue
+        fi
+        if ! fIsBash $tFile; then
+            continue
+        fi
+
+        if ! bash -n $tFile >/dev/null 2>&1; then
+            tFile=${tFile%%:*}
+            fReport 0 1 $tFile "bash syntax error" $LINENO
+        fi
+    done
+
+    if [[ -n "$gFileList" ]]; then
+        let ++gErr
+        echo
+        echo "These bash files had syntax errors:"
+        echo "$gFileList" | fmt -w 10
+        echo
+    fi
+    return 0
+} # fCheckSyntax
 
 # --------------------
-fCheckNotRaw()
-{
+fCheckShell() {
+    local tFile
+    local tResult
+    local tSkip
+
+    tResult=$(git config --get --bool gitproj.hook.check-bash-shell)
+    if [[ "$tResult" != "true" ]]; then
+        return 0
+    fi
+    if ! which shellcheck >/dev/null 2>&1; then
+        echo "Missing shellcheck [$LINENO]"
+        return 0
+    fi
+
+    gFileList=""
+    for tFile in $(git diff --cached --name-only --diff-filter=ACR $gAgainst | tr ' ' '!'); do
+        if [[ ! -f "$tFile" ]]; then
+            continue
+        fi
+        if fIsBinary $tFile; then
+            continue
+        fi
+        if ! fIsBash $tFile; then
+            continue
+        fi
+
+        tSkip='SC1090,SC2003,SC2086,SC2088,SC2155,SC2164,SC2219,SC2230,SC2103,SC2181'
+        if ! shellcheck -x -e $tSkip "$tFile" >/dev/null 2>&1; then
+            echo "Warning: shellcheck errors in $tFile. See bash-lint [$LINENO]" >&2
+        fi
+    done
+
+    if [[ -n "$gFileList" ]]; then
+        echo
+        echo "These bash files had shellcheck errors:"
+        echo "$gFileList" | fmt -w 10
+        echo
+    fi
+    return 0
+} # fCheckShell
+
+# --------------------
+fFixFmt() {
+    local tFile
+    local tResult
+
+    tResult=$(git config --get --bool gitproj.hook.fix-bash-fmt)
+    if [[ "$tResult" != "true" ]]; then
+        return 0
+    fi
+    if ! which bash-fmt >/dev/null 2>&1; then
+        echo "Missing bash-fmt [$LINENO]"
+        return 0
+    fi
+
+    gFileList=""
+    for tFile in $(git diff --cached --name-only --diff-filter=ACR $gAgainst | tr ' ' '!'); do
+        if [[ ! -f "$tFile" ]]; then
+            continue
+        fi
+        if fIsBinary $tFile; then
+            continue
+        fi
+        if ! fIsBash $tFile; then
+            continue
+        fi
+
+        if ! bash-fmt "$tFile" >/dev/null 2>&1; then
+            echo "Warning: Reformatted $tFile. See bash-fmt [$LINENO]" >&2
+        fi
+    done
+
+    if [[ -n "$gFileList" ]]; then
+        echo
+        echo "These bash files were reformatted:"
+        echo "$gFileList" | fmt -w 10
+        echo
+    fi
+    return 0
+} # fFixFmt
+
+# --------------------
+fCheckNotRaw() {
     local tFile
     local tResult
 
     tResult=$(git config --get --bool gitproj.hook.check-in-raw)
-    if [ "$tResult" != "true" ]; then
+    if [[ "$tResult" != "true" ]]; then
         return 0
     fi
 
@@ -224,7 +338,7 @@ fCheckNotRaw()
         fReport 1 $? $tFile "Do not commit files in raw/" $LINENO
     done
 
-    if [ -n "$gFileList" ]; then
+    if [[ -n "$gFileList" ]]; then
         let ++gErr
         echo
         echo "These files should not be managed in git:"
@@ -243,40 +357,39 @@ EOF
 } # fCheckNotRaw
 
 # --------------------
-fCheckBigFiles()
-{
+fCheckBigFiles() {
     local tMaxSize
     local tSize
     local tFile
     local tResult
 
     tResult=$(git config --get --bool gitproj.hook.check-for-big-files)
-    if [ "$tResult" != "true" ]; then
+    if [[ "$tResult" != "true" ]]; then
         return 0
     fi
 
     tMaxSize=$(git config --get --int gitproj.hook.binary-file-size)
-    if [ -z "$tMaxSize" ]; then
+    if [[ -z "$tMaxSize" ]]; then
         tMaxSize=10000
     fi
-    if [ $tMaxSize -le 10000 ]; then
+    if [[ $tMaxSize -le 10000 ]]; then
         tMaxSize=10000
     fi
 
     gFileList=""
     for tFile in $(git diff --cached --name-only --diff-filter=ACR $gAgainst | tr ' ' '!'); do
-        if [ ! -f "$tFile" ]; then
+        if [[ ! -f "$tFile" ]]; then
             continue
         fi
         if ! fIsBinary $tFile; then
             continue
         fi
         tSize=$(ls -l $tFile | awk '{print $5}')
-        if [ $tSize -gt $tMaxSize ]; then
+        if [[ $tSize -gt $tMaxSize ]]; then
             fReport 0 1 $tFile "size $tSize > $tMaxSize" $LINENO
         fi
     done
-    if [ -n "$gFileList" ]; then
+    if [[ -n "$gFileList" ]]; then
         let ++gErr
         echo
         echo "These files were > $tMaxSize:"
@@ -305,13 +418,14 @@ if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
 fi
 
 gVerbose=$(git config --get --bool gitproj.hook.verbose)
-if [ -z "$gVerbose" ]; then
+if [[ -z "$gVerbose" ]]; then
     gVerbose=true
 fi
 fEnabled
 fCheckFileNames
 fCheckWhiteSpace
 fCheckForTabs
+fCheckSyntax
 fCheckNotRaw
 fCheckBigFiles
 
